# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15QGPkxcHuUlyekSo-C0V1Lgag__jSoFv
"""

print ("Hello, world")

i = 1
while i < 11:
  print(i)
  i = i + 1